name: get price

on:
#   schedule:
#   - cron:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GOOGLE_API_KEY }}
    #     workload_identity_provider: "projects/169411888623/locations/global/workloadIdentityPools/github-tracker/providers/github"
    #     service-account: "domcronjob@redtracker-418718.iam.gserviceaccount.com"
    - name: Setup python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.11'
    - name: install python packages
      run:
        python -m pip install --upgrade pip
        pip install requests google-api-python-client google-auth-httplib2 google-auth-oauthlib
    - name: call av api
      env:
        AV_KEY: ${{ secrets.AV_API_KEY }}
      run: python av_api.py
